version: "2"
run:
  modules-download-mode: readonly
linters:
  disable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
